# Site settings
title: savory-ml
email: markus.woodson1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: markus125249
github_username:  mwoodson1

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  food:
    output: true
    permalink: /food/:path/
  projects:
    output: true
    permalink: /projects/:path/
